### ISSUE TITLE
Error: Cannot set property 'owner' of undefined

### ISSUE THREAD

**Issue by cgabdel** [aceymer/courseplanner#1]
Hi Lars you did a very good job.
First of all I beg pardon for asking here, but I didn't find anything like forum or mail list or whatever, so..
When I try to add a new syllabus just after a fresh install v0.3.03, I got this error message,

angular.js:13424 TypeError: Cannot set property 'owner' of undefined
    at Scope.$scope.createSyllaus (syllabus.controller.js:25)
    at fn (eval at <anonymous> (angular.js:14268), <anonymous>:4:230)
    at expensiveCheckFn (angular.js:15281)
    at callback (angular.js:24808)
    at Scope.$eval (angular.js:17025)
    at Scope.$apply (angular.js:17125)
    at HTMLButtonElement.<anonymous> (angular.js:24813)
    at HTMLButtonElement.jQuery.event.dispatch (jquery.js:4737)
    at HTMLButtonElement.elemData.handle (jquery.js:4549)(anonymous function) @ angular.js:13424(anonymous function) @ angular.js:10137Scope.$apply @ angular.js:17130(anonymous function) @ angular.js:24813jQuery.event.dispatch @ jquery.js:4737elemData.handle @ jquery.js:4549

**Comment by aceymer** [comment]
Sorry about that :(
The quick fix is to change: 

```
$scope.isOwner = function(syllabus){
     return Auth.getCurrentUser()._id === syllabus.owner._id; 
}
```

with:

```
$scope.isOwner = function(syllabus){
     if(syllabus.owner){
      return Auth.getCurrentUser()._id === syllabus.owner._id;
     }
}
```

I will try to update the code ASAP.

**Comment by cgabdel** [comment]
still the same problem.

**Comment by aceymer** [comment]
Ok.. I will look into it tonight

**Comment by aceymer** [comment]
Ohh I see the issue. We have not defined $scope.newSyllabus before we use it..
Add this:

```
.......
.controller('SyllabusCtrl', function($scope, $state, SyllabusService, socket, Auth) {
    $scope.isAuthenticated = Auth.isLoggedIn;
    $scope.propToSortOn = 'title';
    $scope.reverse = false;
    //Add the line below....
    $scope.newSyllabus = {};
```

I will commit this to v 0.3.04 tonight.

**Comment by cgabdel** [comment]
it works, but there is a small issue, I have to do a manual refrech, to see the delete button.

**Comment by aceymer** [comment]
Just added v0.3.05, can you try that?
And what browser are you using?
Are there any errors in the console?

**Comment by cgabdel** [comment]
it works, but I have to do a manual refresh to see the delete button, I use firefox and chrome, no error message. it's just 108 messages:

curent:  569e69cc1ab998358d37667d      syllabus.controller.js:19 
owner:  569e69cc1ab998358d37667d      syllabus.controller.js:20 
curent:  569e69cc1ab998358d37667d      syllabus.controller.js:19 
owner:  569e69cc1ab998358d37667d      syllabus.controller.js:20 
curent:  569e69cc1ab998358d37667d      syllabus.controller.js:19 
owner:  569e69cc1ab998358d37667d      syllabus.controller.js:20
etc...

**Comment by aceymer** [comment]
Removed the console logs in 0.3.06
I cannot reproduce your error!
It could be a load issue. If user is loaded to late compared to the syllabus.

I will dig deeper...

**Comment by aceymer** [comment]
Can you try v0.3.07 
Changed ng-show with ng-if (should not matter, but your error is strange)

**Comment by cgabdel** [comment]
I'm sorry but still same problem :(

**Comment by aceymer** [comment]
What node and angular version are you using?
And are you working on windows 10?
And are you logged in as admin or test?
I just cannot reproduce the error :(

**Comment by cgabdel** [comment]
hopefully this will help

OSX 10.9.5 
node v5.9.0
angular-fullstack v3.5.0
AngularJS v1.5.3
logged in as admin
