### ISSUE TITLE
MongoError: Failed to parse 'limit' field must be numeric

### ISSUE THREAD

**Issue by cgabdel** [aceymer/courseplanner#2]
{"name":"MongoError","message":"Failed to parse: { find: \"syllabuses\", filter: {}, sort: { title: 1 }, projection: { title: 1, lecturer: 1, year: 1, owner: 1 }, limit: \"25\" }. 'limit' field must be numeric.","waitedMS":0,"ok":0,"errmsg":"Failed to parse: { find: \"syllabuses\", filter: {}, sort: { title: 1 }, projection: { title: 1, lecturer: 1, year: 1, owner: 1 }, limit: \"25\" }. 'limit' field must be numeric.","code":9}

It's related with MongoDB 3.2.1 problems, but I don't know how to fix it.

**Comment by aceymer** [comment]
What's your mongoose version?
And it seems limit is sent as a string, not a number.
How did you send the limit?

**Comment by cgabdel** [comment]
mongoose 4.1.2
i get this message after à fresh install of untouched v0.4.01

**Comment by aceymer** [comment]
Hmm I will change that to version 4.2 and I will try to make a clean install on my machine to see if I get the error. 
How did you get the error?
Just after login?

**Comment by cgabdel** [comment]
yes, i think this was an issue with version of mongodb

**Comment by aceymer** [comment]
But how did you get the error? Just by starting the app and logging in?

**Comment by cgabdel** [comment]
yes, I get the error before the generation of Syllabuses, I tried with postman, same thing too.

**Comment by aceymer** [comment]
Can you try to run "npm list" command. It will show you all dependencies in your project. What version does it say for mongoose?

**Comment by cgabdel** [comment]
mongoose@4.4.12

**Comment by aceymer** [comment]
Got the error after update to mongodb 3.2--
Let me look into a fix ASAP!

**Comment by aceymer** [comment]
Please try version 0.4.02 or master. This should be solved now!

**Comment by cgabdel** [comment]
Problem solved!

**Comment by cgabdel** [comment]
can you please, since you are still in the v3.2-- check the problem of button delete, is it still there ?.

**Comment by aceymer** [comment]
No issues here with the delete button. Tried on a windows machine to.. Can you send me a screenshot where the button is gone?

**Comment by cgabdel** [comment]
I'll try to do a screen recorde

**Comment by cgabdel** [comment]
it seems that sorting button doesn't work

**Comment by aceymer** [comment]
Hehhe ok.. Guess its a good thing I was asked to do some testing.. Seems I got plenty of bugs.. Do you get an error?

**Comment by aceymer** [comment]
fixed in 0.4.03

**Comment by cgabdel** [comment]
I believe that is because the new version of mongodb, but you made a very good job.

**Comment by aceymer** [comment]
It was my last commit, got to trigger happy and added number parsing in 2 places. One was sort, and that was a mistake.

**Comment by aceymer** [comment]
Fixed on master as well

**Comment by cgabdel** [comment]
The problem is resolved, but it is normal that it does not sort by page ;)

**Comment by aceymer** [comment]
;)
