### ISSUE TITLE
Courseplanner app delete button problem.

### ISSUE THREAD

**Issue by cgabdel** [aceymer/courseplanner#3]
Here is the video that shows the problem of the delete button, you can also notice that sorting is not per page.
I hope it may help.
https://youtu.be/ZA-Wcpx4Unw

**Comment by aceymer** [comment]
Now I see the problem.. I was thinking it was when you launched the app. Not when you created a new one! 
Let me find a fix tonight.

**Comment by aceymer** [comment]
Try version 0.4.04 (or current master) I have changed the way I handle data after a create of syllabus.

**Comment by cgabdel** [comment]
angular.js:13424 TypeError: Cannot read property 'indexOf' of undefined
    at Socket.<anonymous> (socket.service.js:36)
    at socket.js:24
    at angular.js:18953
    at completeOutstandingRequest (angular.js:5824)
    at angular.js:6100

**Comment by cgabdel** [comment]
After a long research, I finally came across the solution, a simple downgrade to v3.0.11 of mongodb had resolved the problem.
I recommend staying on the v4.0.03 release to avoid the last error console,
and comment out the line client/app/syllabus/syllabus.controller.js:61

and thank you lars for taking the time to write and share this course with us.

**Comment by aceymer** [comment]
When did you get the error?
On create syllabus?
Maybe I can find a fix!

And happy if you can use the course :)

**Comment by cgabdel** [comment]
Yes, and when I click delete, I have this message in the console,
Syllabus deleted Resource {$promise: Promise, $resolved: true}   syllabus.controller.js:79

**Comment by aceymer** [comment]
ok.. looking into it

**Comment by aceymer** [comment]
Try now! v0.4.05. (or master)
If you want me to remove the animation I will ;) it is a bit overkill maybe :D

**Comment by cgabdel** [comment]
Well done! 
I have to say  'hats off'
